export const routes = {
  home: "/",
  login: "/login",
  signup: "/signup",
  welcome: "/welcome",
  anamnesis: "/onboarding/anamnesis",
  triage: "/onboarding/triage",
  triageResult: "/onboarding/triage/result",
  investigation: "/onboarding/investigation",
  operationalAssessment: "/onboarding/operational-assessment",
  initialPlan: "/onboarding/initial-plan",
  dashboard: "/dashboard",
  checkout: "/checkout",
  plan: "/plan",
  progression: "/progression",
  checkIn: "/check-in",
  profile: "/profile",
  reassessment: "/reassessment",
  cycleReport: "/cycle-report",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminPlans: "/admin/plans",
  adminPayment: "/admin/payment",
  adminTriage: "/admin/triage",
  adminInvestigation: "/admin/investigation",
  adminOperationalAssessment: "/admin/operational-assessment",
} as const;
